version: "3"

networks:
  api:
    driver: bridge
  mongo:
    driver: bridge

services:
  integration_tests:
    build: integration_tests
    depends_on:
      - audit_api
    environment:
      AUDIT_API_URL: "http://audit_api:80"
      AUDIT_API_KEY: supersecret1
      AUDIT_API_MONGO_URI: mongodb://root:example@mongo:27017/
    command: go test -v ./...
    networks:
      - api
      - mongo

  audit_api:
    build: .
    depends_on:
      - mongo
    # restart: on-failure
    expose:
      - "80"
    ports:
      - "8080:80"
    environment:
      AUDIT_API_HTTP_LISTEN: ":80"
      AUDIT_API_HTTP_TIMEOUT: 10s
      AUDIT_API_MONGO_URI: mongodb://root:example@mongo:27017/
      AUDIT_API_KEY: supersecret1
    networks:
      - mongo
      - api

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo