version: "3"

networks:
  mongo:
    driver: bridge

services:
  audit_api:
    build: .
    depends_on:
      - mongo
    # restart: on-failure
    ports:
      - "8888:80"
    environment:
      AUDIT_API_HTTP_LISTEN: ":80"
      AUDIT_API_HTTP_TIMEOUT: 10s
      ME_CONFIG_MONGO_URL: mongodb://root:example@mongo:27017/
    networks:
      - mongo

  mongo:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - mongo